name: Inputs and Outputs.

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Skip deployment and only print build output'
                type: boolean
                default: false
            target:
                description: 'Which environment the workflow will target'
                required: true
                type: string
            tag:
                description: 'Release from which to build and deploy'
                type: choice
                options: [v1, v2, v3]
                default: v3
            build-status:
                description: 'Choose the build status for the demo'
                type: choice
                options: [success, failure]
                default: success
            
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.build.outputs.tag }}
            status: ${{ steps.build.outputs.status }}
        steps:
            - name: 'Print output path'
              run: |
                echo "Value GITHUB_OUTPUT: $GITHUB_OUTPUT"

            - name: 'Build'
              id: build
              run: |
                echo "tag=${{ inputs.tag }}" > $GITHUB_OUTPUT
                echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
        
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: int
        if: ${{ !inputs.dry-run && needs.build.outputs.status == 'success' }}

        steps:
            - name: 'Deploy'
              run: |
                echo "Deploying to '${{ github.environment.name }}' using tag '${{ needs.build.outputs.tag }}'."
